In [4]:
%cd ..
%load_ext autoreload
%autoreload 2

/home/moshida/EUVlitho


In [2]:
import numpy as np
from elitho import pupil, const

In [3]:
linput, minput, xinput, ninput = pupil.find_valid_pupil_points(const.Nrange)

In [4]:
th = 8
xinput = np.where(xinput >= th, 1, 0)
xinput

array([0, 0, 0, ..., 0, 0, 0], shape=(8705,))

In [7]:
from elitho.utils import saver

saver.save_pupil_points("output.csv", linput, minput, xinput, ninput)

In [8]:
const.lindex

array([-75, -74, -73, ...,  73,  74,  75], shape=(8705,))

In [1]:
a = [1,2,3,4,5]

In [2]:
a[slice(2,4)]

[3, 4]

In [12]:
import numpy as np
from elitho import diffraction_amplitude, const
from elitho import descriptors, diffraction_order
dod = descriptors.DiffractionOrderDescriptor(6.0, diffraction_order.rounded_diamond)
sx0 = 2.0 * const.pi / const.dx * 0 / const.ndivs + const.kx0
sy0 = 2.0 * const.pi / const.dy * 0 / const.ndivs + const.ky0

diffraction_amplitude.diffraction_amplitude("X", np.ones((2048, 2048)), sx0, sy0, dod)

array([[[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
        ...,
        [0.+